### ISSUE TITLE
バトランレビュー

### ISSUE THREAD

**Issue by hisaju** [issei-yoshi/mypalette#154]
※ 確認できたらcloseしてください

## サービスについて

* シンプルで分かりやすいペインに刺しにいってるところはよかったと思います。
* 拡張方向としては例えば色相環などを用いてメインカラーと相性のいい色をレコメンドしてくれたりするとより使いたくなりそうだなと思いました。
* あと初見で何のサービスか分かりづらかったので使い方やサイトの目的などが分かるような文言やチュートリアル的なものがあると分かりやすいかなと。
* 会員登録メリットも少し薄いかなと思ったので、会員登録後に使える機能をもっと増やしてもよさそうですね。

## コードについて

* コードは一通り見ましたが、すっきりときれいに書かれていて特に指摘する点はないかなと思いました。
* テストも一定書かれていたのとREADMEもきれいにまとまっていたので就活する上では全く問題ないかなと。
* しいてあげるとすれば、もう少しコードに厚みがあるとより担当者にも刺さる気はしたので、機能に厚みをもたせられるとベターかなと思いました。

**Comment by issei-yoshi** [comment]
ひさじゅさん、レビューいただき、ありがとうございました！
本サービスはもちろんのこと、今後の開発にも活かせる部分が多くあると思いました。

いただいたレビューを元に日々精進していきます！
ありがとうございます！
